name: Test GitHub Action

on:
  workflow_dispatch:   # allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: 23f3001196@ds.study.iitm.ac.in
        run: echo "Hello, world! GitHub Actions is working."
